table 'All Analysis with AI Final'
	lineageTag: 120d8f58-c573-4745-88ad-5d610f69b93c

	measure 'Stocks Scanned' = DISTINCTCOUNT('All Analysis with AI Final'[stock])
		formatString: 0
		lineageTag: 8f2f5fd4-8d57-4b53-9a60-42d6484cf001

	measure 'Buy Signals' = CALCULATE(DISTINCTCOUNT('All Analysis with AI Final'[stock]), 'All Analysis with AI Final'[long_term_signal] = "BUY")
		formatString: 0
		lineageTag: 8f2f5fd4-8d57-4b53-9a60-42d6484cf002

	measure 'Sell Signals' = CALCULATE(DISTINCTCOUNT('All Analysis with AI Final'[stock]), 'All Analysis with AI Final'[long_term_signal] = "SELL")
		formatString: 0
		lineageTag: 8f2f5fd4-8d57-4b53-9a60-42d6484cf003

	measure 'Hold Signals' = CALCULATE(DISTINCTCOUNT('All Analysis with AI Final'[stock]), 'All Analysis with AI Final'[long_term_signal] = "HOLD")
		formatString: 0
		lineageTag: 8f2f5fd4-8d57-4b53-9a60-42d6484cf004

	measure 'Average Confidence' = DIVIDE(AVERAGE('All Analysis with AI Final'[confidence]), 100)
		formatString: 0.0%
		lineageTag: 8f2f5fd4-8d57-4b53-9a60-42d6484cf005

	measure 'Average Confidence Score' = AVERAGE('All Analysis with AI Final'[confidence])
		formatString: 0
		lineageTag: 8f2f5fd4-8d57-4b53-9a60-42d6484cf006

	measure 'Average Risk Reward' = AVERAGE('All Analysis with AI Final'[risk_reward])
		formatString: 0.00
		lineageTag: 8f2f5fd4-8d57-4b53-9a60-42d6484cf007

	measure 'Selected Price' = MAX('All Analysis with AI Final'[current_price])
		formatString: ₹#,0.00
		lineageTag: 8f2f5fd4-8d57-4b53-9a60-42d6484cf008

	measure 'Selected Change %' = DIVIDE(MAX('All Analysis with AI Final'[change_pct]), 100)
		formatString: 0.00%;-0.00%
		lineageTag: 8f2f5fd4-8d57-4b53-9a60-42d6484cf009

	measure 'Selected RSI' = MAX('All Analysis with AI Final'[rsi])
		formatString: 0.00
		lineageTag: 8f2f5fd4-8d57-4b53-9a60-42d6484cf010

	measure 'Selected MACD' = MAX('All Analysis with AI Final'[macd])
		formatString: 0.000
		lineageTag: 8f2f5fd4-8d57-4b53-9a60-42d6484cf011

	measure 'Selected EMA20' = MAX('All Analysis with AI Final'[ema20])
		formatString: ₹#,0.00
		lineageTag: 8f2f5fd4-8d57-4b53-9a60-42d6484cf012

	measure 'Selected EMA50' = MAX('All Analysis with AI Final'[ema50])
		formatString: ₹#,0.00
		lineageTag: 8f2f5fd4-8d57-4b53-9a60-42d6484cf013

	measure 'Selected EMA200' = MAX('All Analysis with AI Final'[ema200])
		formatString: ₹#,0.00
		lineageTag: 8f2f5fd4-8d57-4b53-9a60-42d6484cf014

	measure 'Selected VWAP' = MAX('All Analysis with AI Final'[vwap])
		formatString: ₹#,0.00
		lineageTag: 8f2f5fd4-8d57-4b53-9a60-42d6484cf015

	measure 'Selected Volume' = MAX('All Analysis with AI Final'[volume])
		formatString: #,0
		lineageTag: 8f2f5fd4-8d57-4b53-9a60-42d6484cf016

	measure 'Selected Avg Volume' = MAX('All Analysis with AI Final'[avg_volume])
		formatString: #,0
		lineageTag: 8f2f5fd4-8d57-4b53-9a60-42d6484cf017

	column date
		dataType: dateTime
		formatString: General Date
		lineageTag: 17589745-6f30-4e10-b7de-afb29d6b6606
		summarizeBy: none
		sourceColumn: date

		variation Variation
			isDefault
			relationship: fb1c5299-447e-46ed-99b1-117fb766ceaa
			defaultHierarchy: LocalDateTable_38edc2f5-1115-4ef9-819a-26ab38413dca.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column stock
		dataType: string
		lineageTag: df2cf958-f8f2-4cc5-8fdb-f7759c21174e
		summarizeBy: none
		sourceColumn: stock

		annotation SummarizationSetBy = Automatic

	column current_price
		dataType: double
		lineageTag: 56da2073-a692-4b2b-89bf-af9af35ad668
		summarizeBy: sum
		sourceColumn: current_price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column change_pct
		dataType: double
		lineageTag: 951d667a-de66-437a-aa17-e30306749152
		summarizeBy: sum
		sourceColumn: change_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column rsi
		dataType: double
		lineageTag: ecae4217-461a-48ba-92cb-b468f8186223
		summarizeBy: sum
		sourceColumn: rsi

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ema20
		dataType: double
		lineageTag: ebd997dd-05fa-4aa8-99bb-913befae5a28
		summarizeBy: sum
		sourceColumn: ema20

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ema50
		dataType: double
		lineageTag: e4f94868-7296-412a-9f01-46b067dd2411
		summarizeBy: sum
		sourceColumn: ema50

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ema200
		dataType: double
		lineageTag: 5d913d90-c63d-4c1d-86f4-4ab04cca0247
		summarizeBy: sum
		sourceColumn: ema200

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column vwap
		dataType: double
		lineageTag: 527ebbc2-e9b1-4525-80c6-772ce1857c2d
		summarizeBy: sum
		sourceColumn: vwap

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column macd
		dataType: double
		lineageTag: 7d76ce0f-2760-464a-9ddc-89ca7697724e
		summarizeBy: sum
		sourceColumn: macd

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column volume
		dataType: int64
		formatString: 0
		lineageTag: d96ec947-f591-430d-b50d-e99e9037774b
		summarizeBy: sum
		sourceColumn: volume

		annotation SummarizationSetBy = Automatic

	column avg_volume
		dataType: int64
		formatString: 0
		lineageTag: cf335f12-cb66-4cdd-a29b-3f82b9cf6135
		summarizeBy: sum
		sourceColumn: avg_volume

		annotation SummarizationSetBy = Automatic

	column confidence
		dataType: int64
		formatString: 0
		lineageTag: 2883fb9c-bdfe-476b-9e2e-f1de52d528ed
		summarizeBy: sum
		sourceColumn: confidence

		annotation SummarizationSetBy = Automatic

	column entry
		dataType: double
		lineageTag: 1df3d806-ddd6-4927-a7d9-6533bc75e67a
		summarizeBy: sum
		sourceColumn: entry

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column target_1
		dataType: double
		lineageTag: 7d1c14f7-c739-45eb-bb5d-67d480339254
		summarizeBy: sum
		sourceColumn: target_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column target_2
		dataType: double
		lineageTag: ce6988a9-6e3b-41b5-af1e-718ae3f9d415
		summarizeBy: sum
		sourceColumn: target_2

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column stop_loss
		dataType: double
		lineageTag: b918e9d6-d16f-4d43-9301-851b93a2aac1
		summarizeBy: sum
		sourceColumn: stop_loss

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trend
		dataType: string
		lineageTag: 2d7861f3-a31f-45a9-8a38-9a7b42d12ca4
		summarizeBy: none
		sourceColumn: trend

		annotation SummarizationSetBy = Automatic

	column intraday_signal
		dataType: string
		lineageTag: 30f9ad97-953f-47d9-b1ba-0798572b71b3
		summarizeBy: none
		sourceColumn: intraday_signal

		annotation SummarizationSetBy = Automatic

	column long_term_signal
		dataType: string
		lineageTag: 7672f8b5-5674-43d6-a620-262b911768a7
		summarizeBy: none
		sourceColumn: long_term_signal

		annotation SummarizationSetBy = Automatic

	column timeframe
		dataType: string
		lineageTag: 16df3737-dda7-4644-9e57-21c9d3d74c34
		summarizeBy: none
		sourceColumn: timeframe

		annotation SummarizationSetBy = Automatic

	column timeframe_t2
		dataType: string
		lineageTag: cde7f57d-fd54-4bc3-bbb0-e68bf6566aed
		summarizeBy: none
		sourceColumn: timeframe_t2

		annotation SummarizationSetBy = Automatic

	column risk_reward
		dataType: double
		lineageTag: 8cceb75a-e10e-459c-bd9c-29e5128edf6a
		summarizeBy: sum
		sourceColumn: risk_reward

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column rank
		dataType: int64
		formatString: 0
		lineageTag: 894af94d-5c83-4c13-a102-ba4a04c13c2a
		summarizeBy: sum
		sourceColumn: rank

		annotation SummarizationSetBy = Automatic

	column RequiredStocks = ISBLANK(RELATED(Stocklist[Stocks]))
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 6c05045f-baf1-4aaa-ae43-1efb675f5e00
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Trend Indicator' =
			VAR TrendValue = UPPER(COALESCE([trend], ""))
			RETURN
				SWITCH(
					TRUE(),
					TrendValue IN { "BULLISH", "UPTREND", "UP TREND" }, "🟢 ↑ Uptrend",
					TrendValue = "NEUTRAL", "🟡 ● Neutral",
					TrendValue IN { "BEARISH", "DOWNTREND", "DOWN TREND" }, "🔴 ● Downtrend",
					"🟡 ● " & COALESCE([trend], "Watch")
				)
		lineageTag: d4bdf9a2-8ae4-40f8-9081-8fb72c8d1001
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Intraday Indicator' =
			VAR SignalValue = UPPER(COALESCE([intraday_signal], ""))
			RETURN
				SWITCH(
					TRUE(),
					SignalValue = "BUY", "🟢 ↑ BUY",
					SignalValue = "SELL", "🔴 ↓ SELL",
					SignalValue IN { "HOLD", "WATCH" }, "🟡 → " & SignalValue,
					"🟡 → WATCH"
				)
		lineageTag: d4bdf9a2-8ae4-40f8-9081-8fb72c8d1002
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Long Term Indicator' =
			VAR SignalValue = UPPER(COALESCE([long_term_signal], ""))
			RETURN
				SWITCH(
					TRUE(),
					SignalValue = "BUY", "🟢 ↑ BUY",
					SignalValue = "SELL", "🔴 ↓ SELL",
					SignalValue IN { "HOLD", "WATCH" }, "🟡 → " & SignalValue,
					"🟡 → WATCH"
				)
		lineageTag: d4bdf9a2-8ae4-40f8-9081-8fb72c8d1003
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Rank Indicator' =
			SWITCH(
				TRUE(),
				[rank] <= 9, "🟢 " & FORMAT([rank], "00"),
				[rank] <= 18, "🟡 " & FORMAT([rank], "00"),
				"🔴 " & FORMAT([rank], "00")
			)
		lineageTag: d4bdf9a2-8ae4-40f8-9081-8fb72c8d1004
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Combined Score' =
			VAR TrendValue = UPPER(COALESCE([trend], ""))
			VAR IntradayValue = UPPER(COALESCE([intraday_signal], ""))
			VAR LongTermValue = UPPER(COALESCE([long_term_signal], ""))
			VAR TrendScore = SWITCH(TRUE(), TrendValue IN { "BULLISH", "UPTREND", "UP TREND" }, 30, TrendValue = "NEUTRAL", 15, 0)
			VAR IntradayScore = SWITCH(IntradayValue, "BUY", 25, "HOLD", 12, "WATCH", 12, 0)
			VAR LongTermScore = SWITCH(LongTermValue, "BUY", 25, "HOLD", 12, "WATCH", 12, 0)
			VAR ConfidenceScore = MIN(20, MAX(0, DIVIDE([confidence], 5, 0)))
			VAR RankScore = SWITCH(TRUE(), [rank] <= 9, 5, [rank] <= 18, 2, 0)
			RETURN TrendScore + IntradayScore + LongTermScore + ConfidenceScore + RankScore
		formatString: 0
		lineageTag: d4bdf9a2-8ae4-40f8-9081-8fb72c8d1005
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Combined Signal' =
			VAR TrendValue = UPPER(COALESCE([trend], ""))
			VAR IntradayValue = UPPER(COALESCE([intraday_signal], ""))
			VAR LongTermValue = UPPER(COALESCE([long_term_signal], ""))
			VAR PerfectAlignment =
				TrendValue IN { "BULLISH", "UPTREND", "UP TREND" }
					&& IntradayValue = "BUY"
					&& LongTermValue = "BUY"
					&& [confidence] >= 80
					&& [rank] <= 9
			RETURN
				SWITCH(
					TRUE(),
					PerfectAlignment, "🟢 STRONG BUY",
					[Combined Score] >= 75, "🟢 BUY",
					[Combined Score] >= 55, "🟡 WATCH",
					[Combined Score] >= 40, "🟠 CAUTION",
					"🔴 SELL"
				)
		lineageTag: d4bdf9a2-8ae4-40f8-9081-8fb72c8d1006
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Combined Color' =
			SWITCH(
				TRUE(),
				[Combined Score] >= 75, "#16A34A",
				[Combined Score] >= 55, "#CA8A04",
				[Combined Score] >= 40, "#EA580C",
				"#DC2626"
			)
		isHidden
		lineageTag: d4bdf9a2-8ae4-40f8-9081-8fb72c8d1007
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'All Analysis with AI Final' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Prasad\OneDrive\Documents\Intraday Macro\Power BI\All Analysis with AI Final.csv"),[Delimiter=",", Columns=24, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"date", type datetime}, {"stock", type text}, {"current_price", type number}, {"change_pct", type number}, {"rsi", type number}, {"ema20", type number}, {"ema50", type number}, {"ema200", type number}, {"vwap", type number}, {"macd", type number}, {"volume", Int64.Type}, {"avg_volume", Int64.Type}, {"confidence", Int64.Type}, {"entry", type number}, {"target_1", type number}, {"target_2", type number}, {"stop_loss", type number}, {"trend", type text}, {"intraday_signal", type text}, {"long_term_signal", type text}, {"timeframe", type text}, {"timeframe_t2", type text}, {"risk_reward", type number}, {"rank", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

